[[datasets]]
enable_bucket = true
resolution = 1024
random_crop = false
shuffle_caption = false
keep_tokens = 0

  [[datasets.subsets]]
  image_dir = "/workspace/job_files/clean_data" 
  num_repeats = 1
  caption_extension = ".txt"
  class_tokens = 'WIXBSAHA'
