[[datasets]]
enable_bucket = true
resolution = [1024, 1024]
bucket_reso_steps = 64
max_bucket_reso = 2048
min_bucket_reso = 128
bucket_no_upscale = false
batch_size = 3
random_crop = false
shuffle_caption = false

  [[datasets.subsets]]
  image_dir = "/workspace/job_files/clean_data" 
  num_repeats = 3
  caption_extension = ".txt"
